### ISSUE TITLE
Patch working

### ISSUE THREAD

**Issue by mchammer26** [toleda/wireless_half-mini#10]
Patches are working Thanks @toleda . But maximum speed only shows 400 MBit/s. Before 10.12.1 had 867 MBit/s.

**Comment by mchammer26** [comment]
Fixed - Was wrong country code. With right country code, I have the 867 again. Thanks to all. Great work.

**Comment by R1MnTnA** [comment]
@mchammer26 Can you tell me if you are running on 5ghz with 80mhz channel on your router? Do you have a DD-WRT configured router? I still can't get my DW1830 wifi card in MacOS to use the 80mhz channel only 40mhz. Although it works fine in Windows. TIA
